name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build /home/ubuntu/Jupyter_redis/docker --file Dockerfile --tag behimolla/jupyter_redis
    - name: push the image to DockerHub
      run: docker login -u behimolla -p ${{ secrets.DOCKER_TOKEN }} && docker push behimolla/jupyter_redis
